# Generated by Django 5.2.4 on 2025-07-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='nomor_transaksi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
