# Generated by Django 5.2.4 on 2025-07-15 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0002_transaksi_nomor_transaksi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='nomor_transaksi',
        ),
        migrations.CreateModel(
            name='AdjustmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Template')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('adjustment_type', models.CharField(choices=[('depreciation', 'Penyusutan'), ('accrual', 'Akrual'), ('deferral', 'Penangguhan'), ('bad_debt', 'Piutang Tak Tertagih'), ('inventory_adj', 'Penyesuaian Persediaan'), ('prepaid_exp', 'Beban Dibayar Dimuka'), ('unearned_rev', 'Pendapatan Diterima Dimuka'), ('other', 'Lainnya')], max_length=20, verbose_name='Jenis Penyesuaian')),
                ('frequency', models.CharField(choices=[('monthly', 'Bulanan'), ('quarterly', 'Triwulanan'), ('annually', 'Tahunan'), ('custom', 'Custom')], max_length=20, verbose_name='Frekuensi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_processed', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Diproses')),
                ('calculation_method', models.CharField(choices=[('fixed_amount', 'Nominal Tetap'), ('percentage', 'Persentase'), ('balance_based', 'Berdasarkan Saldo'), ('formula', 'Formula Kustom')], default='fixed_amount', max_length=20, verbose_name='Metode Perhitungan')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Nominal Tetap')),
                ('percentage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Persentase')),
                ('custom_formula', models.TextField(blank=True, null=True, verbose_name='Formula Kustom')),
                ('base_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_for_adjustments', to='keuangan.akun', verbose_name='Akun Dasar Perhitungan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_adjustments', to='keuangan.akun', verbose_name='Akun Kredit')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_adjustments', to='keuangan.akun', verbose_name='Akun Debit')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_field', models.CharField(max_length=50, verbose_name='Field Kondisi')),
                ('condition_operator', models.CharField(choices=[('gt', 'Lebih Besar'), ('lt', 'Lebih Kecil'), ('eq', 'Sama Dengan'), ('gte', 'Lebih Besar Sama Dengan'), ('lte', 'Lebih Kecil Sama Dengan')], max_length=10, verbose_name='Operator')),
                ('condition_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nilai Kondisi')),
                ('adjustment_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Pengali Penyesuaian')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.adjustmenttemplate', verbose_name='Template')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField(verbose_name='Awal Periode')),
                ('period_end', models.DateField(verbose_name='Akhir Periode')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='Sudah Dibalik')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.transaksi', verbose_name='Transaksi')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.adjustmenttemplate', verbose_name='Template')),
            ],
        ),
    ]
