# Generated by Django 5.2.4 on 2025-07-20 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0003_remove_transaksi_nomor_transaksi_adjustmenttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustmentrule',
            name='template',
        ),
        migrations.RemoveField(
            model_name='adjustmenttemplate',
            name='base_account',
        ),
        migrations.RemoveField(
            model_name='adjustmenttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='adjustmenttemplate',
            name='credit_account',
        ),
        migrations.RemoveField(
            model_name='adjustmenttemplate',
            name='debit_account',
        ),
        migrations.AddField(
            model_name='akun',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='akun',
            name='kode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='akun',
            unique_together={('user', 'kode')},
        ),
        migrations.DeleteModel(
            name='AdjustmentEntry',
        ),
        migrations.DeleteModel(
            name='AdjustmentRule',
        ),
        migrations.DeleteModel(
            name='AdjustmentTemplate',
        ),
    ]
